#ifndef __RWNX_IWPRIV_CMD_H
#define __RWNX_IWPRIV_CMD_H
#include <net/iw_handler.h>

extern struct iw_handler_def iw_handle;

enum aml_iwpriv_subcmd
{
    AML_IWP_PRINT_VERSION = 1,
    AML_IWP_SET_RATE_LEGACY_CCK = 2,
    AML_IWP_SET_RATE_LEGACY_OFDM = 3,
    AML_IWP_SET_RATE_HT = 4,
    AML_IWP_SET_RATE_VHT = 5,
    AML_IWP_SET_RATE_HE = 6,
    AML_IWP_SET_RATE_AUTO = 7,
    AML_IWP_GET_RF_REG = 8,
    AML_IWP_SET_RF_REG = 9,
    AML_IWP_SET_SCAN_HANG = 10,
    AML_IWP_SET_SCAN_TIME = 11,
    AML_IWP_GET_REG = 12,
    AML_IWP_SET_REG = 13,
    AML_IWP_SET_PS_MODE = 14,
    AML_IWP_SEND_TWT_SETUP_REQ = 15,
    AML_IWP_SEND_TWT_TEARDOWN = 16,
    AML_IWP_GET_EFUSE = 17,
    AML_IWP_SET_EFUSE = 18,
    AML_IWP_RECOVERY = 19,
    AML_IWP_SET_AMSDU_MAX = 20,
    AML_IWP_GET_RATE_INFO = 21,
    AML_IWP_SET_AMSDU_TX = 22,
    AML_IWP_SET_LDPC = 23,
    AML_IWP_GET_STATS = 24,
    AML_IWP_SET_P2P_NOA = 25,
    AML_IWP_SET_P2P_OPPPS = 26,
    AML_IWP_GET_ACS_INFO = 27,
    AML_IWP_GET_AMSDU_MAX = 28,
    AML_IWP_GET_AMSDU_TX = 29,
    AML_IWP_GET_LDPC = 30,
    AML_IWP_GET_TXQ = 31,
    AML_IWP_SET_TX_LFT = 32,
    AML_IWP_GET_TX_LFT = 33,
    AML_IWP_GET_LAST_RX = 34,
    AML_IWP_CLEAR_LAST_RX = 35,
    AML_IWP_SET_MACBYPASS = 36,
    AML_IWP_SET_STOP_MACBYPASS = 37,
    AML_IWP_SET_STBC = 38,
    AML_IWP_GET_STBC = 39,
    AML_IWP_PCIE_TEST = 40,
    AML_COEX_CMD = 41,
    AML_LA_DUMP = 42,
    AML_IWP_SET_PT_CALIBRATION = 43,
    AML_IWP_GET_CHAN_LIST = 44,
    AML_IWP_BUS_START_TEST = 45,
    AML_MEM_DUMP = 46,
    AML_IWP_CCA_CHECK = 47,
};


#endif
